### ISSUE TITLE
Incorrect indentation with closing tags

### ISSUE THREAD

**Issue by vinayhk1989** [prettier/plugin-xml#85] opened 2020-05-13 05:49 UTC
After formatting, I could see the incorrect indentation with closing tags.

Configuration option I have used:
        parser: 'xml',
        tabWidth: 4,
        printWidth: 200,
        xmlSelfClosingTags: true,
        xmlWhitespaceSensitivity: 'ignore'

XML content:
```
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
<edmx:Reference Uri="test">
<edmx:Include Namespace="com.sap.vocabularies.UI.v1" Alias="UI" />
</edmx:Reference>
<edmx:Reference Uri="/opu/odat/test/$metadata">
<edmx:Include Namespace="test2" Alias="test3" />
</edmx:Reference>
<edmx:DataServices>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="testv2704">
<Annotations Target="test4">
<Annotation Term="UI.TextArrangement">

</Annotation>
<Annotation Term="UI.TextArrangement">
</Annotation>
<Annotation Term="Aggregation.ApplySupported">
</Annotation>
</Annotations>
</Schema>
</edmx:DataServices>
</edmx:Edmx>
```

After formatting:
![image](https://user-images.githubusercontent.com/9014933/81775876-44393480-950b-11ea-95ee-0007f6d00754.png)

**Comment by kddeisz** [comment] 2020-05-13 11:20
Yeah, this one is a duplicate of #47. The issue is that it tries to maintain whitespace in nodes that have mixed content (both elements and whitespace nodes). I know you passed `whitespaceIgnore` but at the moment it's still not quite handling it like would be expected. I'm still working on it, but I'm going to track it over on that ticket.

**Closed by kddeisz** 2020-05-13 11:20 UTC
